import type { SceneArchetype } from "./types";

const commonFields: SceneArchetype["optionalFields"] = [
  "subtitle",
  "narrative",
  "supportingCopy",
  "media",
  "narration",
  "hotspots",
  "callToAction",
  "presenterNotes",
  "optionalNextDestinations",
];

const performance: SceneArchetype["behaviour"]["performance"] = {
  premium: ["Layered depth, parallax where safe, richer atmospheric treatment."],
  balanced: ["Preserve composition with moderate overlays and limited simultaneous motion."],
  reduced: ["Use static layers, remove heavy blur, keep reveal order and interaction intact."],
};

export const sceneArchetypeLibrary: SceneArchetype[] = [
  archetype("cinematic-opening", "Cinematic Opening", "Creates a major narrative reset or memory moment before standard navigation appears.", {
    content: ["opening", "section"],
    media: ["image", "video", "audio", "caption"],
    interactions: ["guided-continue", "media-playback"],
    theme: "cinematic-dark",
    motion: "cinematic-reveal",
    transitions: ["fade-through-black", "aperture-open", "spatial-pan", "controlled-hard-cut"],
    nav: "hidden-cinematic",
    density: [1, 2],
    interaction: [0, 2],
    duration: [15_000, 90_000],
    memory: true,
    fields: ["headline"],
    variants: ["system awakening", "brand reveal", "chapter reset", "memory takeover"],
    diff: ["full-field", "center-left delayed", "full-bleed", "delayed statement", "dark-cinematic"],
  }),
  archetype("chapter-title", "Chapter Title", "Resets the room rhythm at a new section without becoming a static title slide.", {
    content: ["section"],
    media: ["image", "video", "none"],
    interactions: ["passive", "guided-continue", "branching-choice"],
    theme: "cinematic-dark",
    motion: "architectural-reveal",
    transitions: ["lateral-architectural-wipe", "vertical-structural-reveal", "light-sweep", "controlled-hard-cut"],
    nav: "minimal",
    density: [1, 2],
    interaction: [0, 2],
    duration: [8_000, 24_000],
    fields: ["headline"],
    variants: ["geometry title", "media strip", "section marker", "proof point"],
    diff: ["section-marker", "edge anchored", "strip or detail", "line reveal", "architectural-depth"],
  }),
  archetype("immersive-environment", "Immersive Environment", "Places the customer inside a control-room setting with restrained spatial depth.", {
    content: ["environment", "system"],
    media: ["image", "video"],
    interactions: ["guided-continue", "hotspot-discovery", "simulation-control"],
    theme: "cinematic-dark",
    motion: "cinematic-reveal",
    transitions: ["depth-push", "spatial-pan", "focus-pull"],
    nav: "minimal",
    density: [1, 3],
    interaction: [1, 4],
    duration: [24_000, 70_000],
    hotspots: true,
    fields: ["headline", "visualNote"],
    variants: ["full-room", "zone focus", "ambient loop", "system activation"],
    diff: ["full-bleed-depth", "lower edge", "full-bleed", "focus drift", "full-bleed-media"],
  }),
  archetype("product-hero", "Product Hero", "Makes a major product visually dominant with precision details available on demand.", {
    content: ["product"],
    media: ["image", "video", "derived"],
    interactions: ["guided-continue", "hotspot-discovery", "orbit-explore", "comparison-scrub"],
    theme: "product-light",
    motion: "product-precision",
    transitions: ["object-led-transition", "media-match-cut", "light-sweep"],
    nav: "visible",
    density: [1, 3],
    interaction: [1, 4],
    duration: [25_000, 65_000],
    hotspots: true,
    fields: ["headline", "technicalLayers"],
    variants: ["dark spotlight", "light studio", "environment-integrated", "material-detail", "human-use"],
    diff: ["dominant-subject", "side rail", "central product", "feature isolation", "light-gallery"],
  }),
  archetype("product-exploded-view", "Product Exploded View", "Explains construction or integration through assembled and separated states.", {
    content: ["product", "system"],
    media: ["image", "derived"],
    interactions: ["step-through", "hotspot-discovery"],
    theme: "architectural-light",
    motion: "product-precision",
    transitions: ["object-led-transition", "layer-reveal", "controlled-hard-cut"],
    nav: "visible",
    density: [2, 4],
    interaction: [2, 4],
    duration: [30_000, 70_000],
    hotspots: true,
    fields: ["headline", "technicalLayers"],
    variants: ["conceptual layers", "assembly steps", "service access", "material stack"],
    diff: ["exploded-axis", "right technical rail", "center layers", "assemble-disassemble", "technical-schematic"],
  }),
  archetype("interactive-hotspot", "Interactive Hotspot", "Supports focused exploration of product or environment features without visual clutter.", {
    content: ["environment", "product", "operator"],
    media: ["image", "video"],
    interactions: ["hotspot-discovery"],
    theme: "immersive-neutral",
    motion: "architectural-reveal",
    transitions: ["focus-pull", "light-sweep", "layer-reveal"],
    nav: "visible",
    density: [2, 4],
    interaction: [3, 5],
    duration: [28_000, 80_000],
    hotspots: true,
    fields: ["headline", "technicalLayers"],
    variants: ["product detail", "room systems", "operator impact", "architectural material", "connected technology"],
    diff: ["image-annotation", "context detail", "anchored media", "selected reveal", "architectural-depth"],
  }),
  archetype("operator-perspective", "Operator Perspective", "Frames a control-room story around human attention, pressure and response.", {
    content: ["operator", "environment"],
    media: ["image", "video", "derived"],
    interactions: ["guided-continue", "simulation-control", "step-through"],
    theme: "operational-dark",
    motion: "human-focus",
    transitions: ["focus-pull", "fade-through-black", "blur-resolve"],
    nav: "minimal",
    density: [1, 3],
    interaction: [1, 4],
    duration: [24_000, 68_000],
    fields: ["headline", "supportingMessage"],
    variants: ["focus narrowing", "shift fatigue", "response choice", "comfort change"],
    diff: ["first-person-field", "center breathing", "environment layer", "stress-to-calm", "dark-cinematic"],
  }),
  archetype("problem-solution", "Problem Solution", "Transforms a customer challenge into a coordinated response in one visual system.", {
    content: ["operator", "system", "process"],
    media: ["image", "derived"],
    interactions: ["guided-continue", "step-through", "simulation-control"],
    theme: "alert-state",
    motion: "operational-response",
    transitions: ["match-cut", "split-panel-transition", "light-sweep"],
    nav: "visible",
    density: [2, 4],
    interaction: [1, 4],
    duration: [28_000, 72_000],
    fields: ["headline", "supportingMessage"],
    variants: ["constraint collapse", "fragment to aligned", "risk resolved", "task simplified"],
    diff: ["single-transform", "two-state lower rail", "same environment", "tension-resolution", "split-spatial"],
  }),
  archetype("before-after", "Before After", "Makes a visual transformation comparable through drag, toggle or timed reveal.", {
    content: ["environment", "product", "operator"],
    media: ["image", "derived"],
    interactions: ["comparison-scrub"],
    theme: "architectural-light",
    motion: "architectural-reveal",
    transitions: ["match-cut", "split-panel-transition", "controlled-hard-cut"],
    nav: "visible",
    density: [1, 3],
    interaction: [2, 5],
    duration: [24_000, 60_000],
    fields: ["headline", "supportingMessage"],
    variants: ["drag divider", "tap toggle", "matched room", "layer reveal"],
    diff: ["comparison-field", "top labels", "dual layer", "divider reveal", "split-spatial"],
  }),
  archetype("system-connection", "System Connection", "Shows products, systems and human outcomes connected inside the room.", {
    content: ["system", "environment"],
    media: ["image", "derived"],
    interactions: ["step-through", "hotspot-discovery"],
    theme: "data-dark",
    motion: "data-intelligence",
    transitions: ["data-trace-transition", "spatial-pan", "layer-reveal"],
    nav: "visible",
    density: [2, 4],
    interaction: [2, 4],
    duration: [30_000, 75_000],
    hotspots: true,
    fields: ["headline", "technicalLayers"],
    variants: ["room ecosystem", "operator-to-system", "service path", "collaboration path"],
    diff: ["spatial-network", "upper outcome rail", "embedded nodes", "trace activation", "technical-schematic"],
  }),
  archetype("data-story", "Data Story", "Presents evidence or quantified logic as one progressive insight, not a dashboard.", {
    content: ["proof", "process"],
    media: ["derived", "none"],
    interactions: ["step-through"],
    theme: "data-dark",
    motion: "data-intelligence",
    transitions: ["data-scan", "data-trace-transition", "controlled-hard-cut"],
    nav: "visible",
    density: [2, 5],
    interaction: [1, 3],
    duration: [25_000, 65_000],
    fields: ["headline", "technicalLayers"],
    variants: ["single metric", "progressive chart", "comparative evidence", "timeline", "spatial data"],
    diff: ["insight-stage", "left proof spine", "data canvas", "progressive annotation", "technical-schematic"],
  }),
  archetype("feature-orbit", "Feature Orbit", "Connects several benefits around one central subject while focusing only one at a time.", {
    content: ["product", "system"],
    media: ["image", "derived"],
    interactions: ["orbit-explore", "step-through"],
    theme: "operational-dark",
    motion: "product-precision",
    transitions: ["object-led-transition", "focus-pull", "light-sweep"],
    nav: "visible",
    density: [2, 4],
    interaction: [2, 5],
    duration: [28_000, 70_000],
    fields: ["headline", "technicalLayers"],
    variants: ["operator features", "room capabilities", "product benefits", "service ecosystem"],
    diff: ["radial-focus", "perimeter labels", "central subject", "focus transfer", "dark-cinematic"],
  }),
  archetype("spatial-journey", "Spatial Journey", "Moves through zones of a room or project environment with clear orientation.", {
    content: ["environment", "proof", "choice"],
    media: ["image", "video", "derived"],
    interactions: ["branching-choice", "hotspot-discovery", "step-through"],
    theme: "immersive-neutral",
    motion: "cinematic-reveal",
    transitions: ["spatial-pan", "depth-push", "focus-pull"],
    nav: "minimal",
    density: [1, 4],
    interaction: [2, 5],
    duration: [30_000, 90_000],
    hotspots: true,
    fields: ["headline", "technicalLayers"],
    variants: ["room zones", "project geography", "plan route", "guided path"],
    diff: ["panorama-zones", "anchored rail", "wide canvas", "zone pan", "full-bleed-media"],
  }),
  archetype("process-sequence", "Process Sequence", "Explains a workflow with one active stage at a time and presenter jump control.", {
    content: ["process", "system"],
    media: ["derived", "image"],
    interactions: ["step-through"],
    theme: "architectural-light",
    motion: "architectural-reveal",
    transitions: ["layer-reveal", "object-led-transition", "data-scan"],
    nav: "visible",
    density: [2, 5],
    interaction: [2, 4],
    duration: [28_000, 75_000],
    fields: ["headline", "technicalLayers"],
    variants: ["delivery path", "incident workflow", "implementation sequence", "lifecycle"],
    diff: ["stage-theatre", "active stage center", "process object", "stage handoff", "technical-schematic"],
  }),
  archetype("comparison", "Comparison", "Compares options through focused visual criteria rather than a primary spreadsheet.", {
    content: ["product", "proof", "system"],
    media: ["image", "derived"],
    interactions: ["step-through", "comparison-scrub"],
    theme: "architectural-light",
    motion: "architectural-reveal",
    transitions: ["split-panel-transition", "match-cut", "controlled-hard-cut"],
    nav: "visible",
    density: [2, 4],
    interaction: [2, 4],
    duration: [28_000, 70_000],
    fields: ["headline", "technicalLayers"],
    variants: ["visual switch", "attribute spotlight", "decision path", "matched scenario"],
    diff: ["criterion-spotlight", "bottom criteria", "dual options", "switch focus", "light-gallery"],
  }),
  archetype("evidence-proof", "Evidence Proof", "Connects credentials and proof to customer value through progressive disclosure.", {
    content: ["proof"],
    media: ["image", "derived", "none"],
    interactions: ["hotspot-discovery", "step-through"],
    theme: "data-dark",
    motion: "data-intelligence",
    transitions: ["data-scan", "vertical-structural-reveal", "quiet-fade"],
    nav: "visible",
    density: [3, 5],
    interaction: [1, 4],
    duration: [28_000, 80_000],
    fields: ["headline", "technicalLayers"],
    variants: ["proof theme", "timeline", "capability reveal", "project geography", "verification layer"],
    diff: ["proof-theatre", "evidence rail", "source wall", "verification reveal", "light-gallery"],
  }),
  archetype("customer-choice", "Customer Choice", "Lets customers choose a route, role or outcome through intentional confirmation.", {
    content: ["choice"],
    media: ["image", "derived"],
    interactions: ["branching-choice"],
    theme: "cinematic-dark",
    motion: "architectural-reveal",
    transitions: ["spatial-pan", "light-sweep", "controlled-hard-cut"],
    nav: "minimal",
    density: [1, 3],
    interaction: [3, 5],
    duration: [20_000, 65_000],
    fields: ["headline"],
    variants: ["spatial destinations", "role choice", "challenge choice", "detail depth"],
    diff: ["choice-environment", "center question", "destination points", "preview-confirm", "architectural-depth"],
  }),
  archetype("voice-guided", "Voice Guided", "Uses optional narration as a guide while keeping visuals and captions complete without audio.", {
    content: ["operator", "system", "process"],
    media: ["audio", "caption", "image", "video"],
    interactions: ["media-playback", "guided-continue", "simulation-control"],
    theme: "operational-dark",
    motion: "human-focus",
    transitions: ["focus-pull", "fade-through-black", "data-scan"],
    nav: "minimal",
    density: [1, 3],
    interaction: [1, 3],
    duration: [30_000, 90_000],
    narration: true,
    fields: ["headline", "supportingMessage"],
    variants: ["caption-led", "voice checkpoints", "operator scenario", "silent mode"],
    diff: ["narration-path", "caption anchored", "visual sequence", "timed checkpoints", "dark-cinematic"],
  }),
  archetype("panoramic-room", "Panoramic Room", "Uses a wide controlled canvas to explore zones without becoming horizontal scrolling.", {
    content: ["environment", "system"],
    media: ["image", "video"],
    interactions: ["hotspot-discovery", "step-through"],
    theme: "cinematic-dark",
    motion: "cinematic-reveal",
    transitions: ["spatial-pan", "depth-push", "media-match-cut"],
    nav: "minimal",
    density: [1, 4],
    interaction: [2, 5],
    duration: [30_000, 90_000],
    hotspots: true,
    fields: ["headline", "technicalLayers"],
    variants: ["wide room", "zone-by-zone", "system sweep", "overview fallback"],
    diff: ["wide-canvas", "zone rail", "panoramic media", "zone focus", "full-bleed-media"],
  }),
  archetype("cinematic-closing", "Cinematic Closing", "Ends a journey with confident synthesis and clear next actions without dense contact clutter.", {
    content: ["closing"],
    media: ["image", "video", "audio", "caption"],
    interactions: ["guided-continue", "branching-choice"],
    theme: "cinematic-dark",
    motion: "cinematic-reveal",
    transitions: ["spatial-pan", "blackout-reset", "fade-through-black"],
    nav: "minimal",
    density: [1, 3],
    interaction: [1, 4],
    duration: [24_000, 70_000],
    memory: true,
    fields: ["headline", "callToAction"],
    variants: ["final hold", "journey loop", "discussion pause", "ambient return"],
    diff: ["final-synthesis", "calm center", "full environment", "convergence hold", "dark-cinematic"],
  }),
];

export const sceneArchetypeMap = Object.fromEntries(sceneArchetypeLibrary.map((item) => [item.id, item])) as Record<
  SceneArchetype["id"],
  SceneArchetype
>;

type ArchetypeOptions = {
  content: SceneArchetype["supportedContentTypes"];
  media: SceneArchetype["supportedMediaTypes"];
  interactions: SceneArchetype["supportedInteractionTypes"];
  theme: SceneArchetype["defaultTheme"];
  motion: SceneArchetype["defaultMotionFamily"];
  transitions: SceneArchetype["supportedTransitions"];
  nav: SceneArchetype["defaultNavigationState"];
  density: [number, number];
  interaction: [number, number];
  duration: [number, number];
  fields: Array<keyof import("../../data/contentTypes").Chapter>;
  variants: string[];
  diff: [string, string, string, string, string];
  narration?: boolean;
  hotspots?: boolean;
  memory?: boolean;
};

function archetype(id: SceneArchetype["id"], name: string, purpose: string, options: ArchetypeOptions): SceneArchetype {
  return {
    id,
    name,
    purpose,
    supportedContentTypes: options.content,
    supportedMediaTypes: options.media,
    supportedInteractionTypes: options.interactions,
    defaultTheme: options.theme,
    supportedThemes: [options.theme, "cinematic-dark", "architectural-light", "operational-dark", "data-dark", "calm-state"],
    defaultMotionFamily: options.motion,
    supportedTransitions: options.transitions,
    defaultNavigationState: options.nav,
    informationDensityRange: options.density,
    interactionLevelRange: options.interaction,
    recommendedDurationRange: options.duration,
    suitableAudiences: ["customer", "presenter", "operations", "technology", "architect", "management"],
    suitablePresentationModes: ["presenter", "selfGuided", "autoPlay"],
    supportsNarration: Boolean(options.narration) || options.media.includes("audio"),
    supportsHotspots: Boolean(options.hotspots),
    supportsAutoplay: true,
    supportsReducedMotion: true,
    supportsTouch: true,
    supportsKeyboard: true,
    supportsMemoryMoment: Boolean(options.memory),
    requiredFields: options.fields,
    optionalFields: commonFields,
    fallbackBehaviour: "Render a calm branded composition with all chapter copy, detail layers and presenter notes preserved.",
    validationRules: [
      { id: "required-fields", severity: "error", description: "Required chapter fields must be present." },
      { id: "density-fit", severity: "warning", description: "Chapter density should fit the archetype range." },
      { id: "interaction-fit", severity: "warning", description: "Chapter interaction level should fit the archetype range." },
      { id: "duration-fit", severity: "info", description: "Recommended duration should match presenter and autoplay pacing." },
    ],
    variants: options.variants.map((variant) => ({ id: slug(variant), name: title(variant), description: `${name} variant for ${variant}.` })),
    behaviour: {
      presenter: ["Advance internal sequence", "Skip animation", "Jump to final state", "Continue to next destination"],
      autoplay: ["Respect configured duration", "Auto-complete optional interactions", "Fail forward on missing media"],
      reducedMotion: ["Replace spatial motion with fades or stepped states", "Preserve content hierarchy"],
      responsive: ["Landscape full-screen first", "Tablet portrait uses anchored selectors instead of webpage stacking"],
      performance,
    },
    differentiation: {
      primaryLayout: options.diff[0],
      textPosition: options.diff[1],
      mediaPosition: options.diff[2],
      revealPattern: options.diff[3],
      backgroundTreatment: options.diff[4],
    },
  };
}

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function title(value: string) {
  return value.replace(/\b\w/g, (letter) => letter.toUpperCase());
}
