import type { Asset } from "../data/contentTypes";

export const assets: Asset[] = [
  {
    id: "opening-background-video",
    type: "video",
    src: "/assets/video/opening/onepws-opening.mp4",
    alt: "OnePWS cinematic opening video.",
    publicSafe: true,
  },
  {
    id: "opening-voiceover-en",
    type: "audio",
    language: "en",
    publicSafe: true,
  },
  {
    id: "opening-control-room-fallback",
    type: "image",
    src: "/assets/source-pdf/p01_000_1536x863.jpg",
    alt: "OnePWS control room console capability presentation hero visual.",
    publicSafe: true,
  },
  {
    id: "ambient-control-room",
    type: "image",
    src: "/assets/source-pdf/p31_059_2078x1168.jpg",
    alt: "Bright OnePWS control-room environment with consoles, video wall and architectural ceiling.",
    publicSafe: true,
  },
  {
    id: "showroom-control-room",
    type: "image",
    src: "/assets/source-pdf/p34_062_1422x800.jpg",
    alt: "OnePWS showroom control room with integrated consoles and wall systems.",
    publicSafe: true,
  },
  {
    id: "project-dfcc-control-room",
    type: "image",
    src: "/assets/source-pdf/p20_050_1781x1016.jpg",
    alt: "DFCC Ahmedabad control room project image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-dfcc-inauguration",
    type: "image",
    src: "/assets/source-pdf/p21_051_1672x940.jpg",
    alt: "DFCC Ahmedabad project proof image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-chandigarh-control-room",
    type: "image",
    src: "/assets/source-pdf/p22_052_1421x800.jpg",
    alt: "Chandigarh ICCC control room project image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-adani-khavda-01",
    type: "image",
    src: "/assets/source-pdf/p23_053_1418x798.jpg",
    alt: "Adani Khavda project image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-adani-khavda-02",
    type: "image",
    src: "/assets/source-pdf/p24_054_1418x798.jpg",
    alt: "Adani Khavda control room project image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-rtgc-andhra-01",
    type: "image",
    src: "/assets/source-pdf/p25_055_1759x986.jpg",
    alt: "RTGC Andhra Pradesh project proof image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-rtgc-andhra-02",
    type: "image",
    src: "/assets/source-pdf/p26_056_1672x941.jpg",
    alt: "RTGC Andhra Pradesh control room image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-apco-ahmedabad",
    type: "image",
    src: "/assets/source-pdf/p27_057_1422x800.jpg",
    alt: "Ahmedabad Police APCO control room image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "project-itms-noida-control-room",
    type: "image",
    src: "/assets/source-pdf/p28_058_1898x1063.jpg",
    alt: "ITMS Noida control room project image from OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "showroom-control-room-wide",
    type: "image",
    src: "/assets/source-pdf/p32_060_2002x1125.jpg",
    alt: "OnePWS showroom wide control-room experience image.",
    publicSafe: true,
  },
  {
    id: "showroom-control-room-detail",
    type: "image",
    src: "/assets/source-pdf/p33_061_2088x1172.jpg",
    alt: "OnePWS showroom control-room detail image.",
    publicSafe: true,
  },
  {
    id: "customer-logo-wall-source",
    type: "image",
    src: "/assets/source-pdf/p12_042_1728x857.jpg",
    alt: "Customer-logo wall extracted from the OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "sap-source",
    type: "image",
    src: "/assets/source-pdf/p05_004_528x271.png",
    alt: "SAP reference image extracted from the OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "manufacturing-equipment-source",
    type: "image",
    src: "/assets/source-pdf/p36_063_495x250.jpg",
    alt: "Manufacturing equipment image extracted from the OnePWS source presentation.",
    publicSafe: true,
  },
  {
    id: "onepws-wordmark-source",
    type: "logo",
    src: "/assets/brand/onepws-logo-black.png",
    alt: "OnePWS Private Limited approved logo.",
    publicSafe: true,
  },
];
