/**
 * Generated by scripts/measure-narration.mjs -- do not edit by hand.
 *
 * Real length of the recorded narration per chapter, used so the remaining-time
 * readout counts what the audience will actually hear instead of an estimate.
 * Run `npm run voiceover:durations` after adding or replacing audio.
 */
export const narrationDurationMs: Record<string, number> = {
  "human-centred-philosophy": 36937,
  "mission-critical-environments": 7602,
  "onepws-positioning": 14028,
};

export function narrationDurationFor(chapterId: string) {
  return narrationDurationMs[chapterId] ?? null;
}
